version: '3.8'

services:
  # БД
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: virtual_bookshelf
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d virtual_bookshelf"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Микросервисы
  user-service:
    build: ./server/user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/virtual_bookshelf
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: app_password
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy

  shelf-service:
    build: ./server/shelf-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/virtual_bookshelf
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: app_password
      SERVER_PORT: 8082
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy

  book-service:
    build: ./server/book-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/virtual_bookshelf
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: app_password
      SERVER_PORT: 8083
    ports:
      - "8083:8083"
    depends_on:
      postgres:
        condition: service_healthy

  gateway:
    build: ./server/gateway
    environment:
      SERVER_PORT: 8080
      USER_SERVICE_URL: http://user-service:8081
      SHELF_SERVICE_URL: http://shelf-service:8082
      BOOK_SERVICE_URL: http://book-service:8083
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - shelf-service
      - book-service

volumes:
  postgres_data: